# Generated by Django 4.2.1 on 2023-05-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0002_covid_delete_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covid',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='covid',
            old_name='total_confirmed_cases',
            new_name='TotalConfirmed',
        ),
        migrations.RenameField(
            model_name='covid',
            old_name='total_deaths_cases',
            new_name='TotalDeaths',
        ),
        migrations.RenameField(
            model_name='covid',
            old_name='total_recovered_cases',
            new_name='TotalRecovered',
        ),
    ]
